name: second_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  carousel_slider: ^5.1.1
  flutter_vector_icons: ^2.0.0
  stylish_bottom_bar: ^1.1.1
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.3
  lucide_icons: ^0.257.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.13.1
  geocoding: ^4.0.0
  location: ^8.0.1
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.2.1
  skeletonizer: ^2.1.1
  intl: ^0.19.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  http: ^1.5.0
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
